### ISSUE TITLE
Questions about expansion factor

### ISSUE THREAD

**Issue by LeeYongHyeok** [tbvjvsladla/MiniRNN#1]
Hello @tbvjvsladla , thank you very much for sharing great work.
It seems to be the first time that both minGRU and minLSTM have been implemented in one library. That's great.
There is 'expansion factor' related content in the experimental section of the paper, and it would be better if it is updated.
PS, the model name of the paper was minGRU, minLSTM (not mini), but I am sorry if it is intended.

**Comment by tbvjvsladla** [comment]
Hello LeeYongHyeok,

Thank you for pointing that out. I have incorporated the expansion factor as mentioned in Appendix C of the paper into the miniRNN.py file. I really appreciate your attention to detail regarding aspects I might have missed.

Regarding the filename "miniRNN.py," I considered alternatives like "WereRNN.py" or "miniLSTM/GRU.py," but eventually settled on this due to a bit of decision fatigue. Naming a file that appropriately captures the essence of the paper is indeed quite challenging. 😅

**Comment by LeeYongHyeok** [comment]
@tbvjvsladla, 
Thank you for solving the issue quickly.
I hope you have a good day.
